#!/bin/bash

#Подключение через ssh на гостевую ОС VM
ssh ngale@192.168.23.115
#https://help.skytap.com/Using_SSH_to_Connect_to_a_Linux_VM.html
#https://support.rackspace.com/how-to/connecting-to-a-server-using-ssh-on-linux-or-mac-os/
